name: SafeBackpack
author: Freeze_Dolphin
main: me.freeze_dolphin.safe_backpack.SafeBackpack
version: 1.1

depend: [CS-CoreLib, Slimefun]

commands: 
  bpdatarelocator: 
    description: "Relocate the slimefun backpack data to this plugin's backpack data"
  itemconvertor: 
    description: "Check and convert the slimefun's backpack items into this plugin's backpack item"

permissions: 
  safebackpack.admin: 
    default: op
  safebackpack.convertor.*:  
    default: false
    children: 
      safebackpack.convertor.auto-run: 
        default: false
      safebackpack.convertor.convert: 
        default: op
  safebackpack.dye.*: 
    default: op
    children: 
      safebackpack.dye.menu: 
        default: false
      safebackpack.dye.color.white: 
        default: false
      safebackpack.dye.color.orange: 
        default: false
      safebackpack.dye.color.magenta: 
        default: false
      safebackpack.dye.color.light-blue: 
        default: false
      safebackpack.dye.color.yellow: 
        default: false
      safebackpack.dye.color.lime: 
        default: false
      safebackpack.dye.color.pink: 
        default: false
      safebackpack.dye.color.gray: 
        default: false
      safebackpack.dye.color.light-gray: 
        default: false
      safebackpack.dye.color.cyan: 
        default: false
      safebackpack.dye.color.purple: 
        default: false
      safebackpack.dye.color.blue: 
        default: false
      safebackpack.dye.color.brown: 
        default: false
      safebackpack.dye.color.green: 
        default: false
      safebackpack.dye.color.red: 
        default: false
      safebackpack.dye.color.black: 
        default: false